= Import IEDs

Importing IEDs is a fundamental aspect of system configuration, regardless of whether it follows the "bottom-up" or "top-down" approach.

To import IEDs into the project:

. Navigate to the *Menu*
. Click on *Import IED*
. Select the file(s) you want to import the IED(s) from

Behind the scenes, *OpenSCD* checks the uniqueness of the IEDs `name` attribute within the project. 
However, there is one exception to this rule, which is `TEMPLATE`. 
This term is reserved to describe template IEDs as opposed to "real" IEDs.

Another crucial check is performed within the `DataTypeTemplates` section. *OpenSCD* ensures there are no conflicts between the imported and existing templates. 
Specifically, it verifies that the ``id``s within `LNodeType`, `DOType`, `DAType`, and `EnumType` are unique in the project. 
The standard outlines two basic procedures to address this situation:

. Make `id` unique: When importing IEDs with connections to data in `DataTypeTemplates` that have ``id``'s already present in the project, the `id` and the `type` attribute can be unified. 
As the IED name must be unique in the project, OpenSCD appends this variable to the `id` and `type` attributes in the `DataTypeTemplates`.
. Use `iedType` attribute: `LNodeType`, `DOType`, `DAType` and `EnumType` all have an attribute called `iedType`, which points to the `type` attribute in the IED section. 
With this attribute, data can be clearly connected to an IED.

NOTE: Currently, OpenSCD only utilizes the first option to ensure that all ``id``s are unique within the `DataTypeTemplates` section.

TIP: See https://iec61850.tissue-db.com/tissue/366[Tissue 366]

